name = "mealstack_client"
target = "javascript"
version = "1.0.0"
gleam = ">= 1.13.0"
# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.62.1 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
modem = ">= 2.0.0 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
rada = ">= 0.2.0 and < 1.0.0"
plinth = ">= 0.4.8 and < 1.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.5.1 and < 1.0.0"

# JavaScript specific configuration (optional)
[javascript]
# Generate TypeScript .d.ts files
typescript_declarations = true

# Which JavaScript runtime to use with `gleam run`, `gleam test` etc.
runtime = "bun"
